### ISSUE TITLE
Ensure POI API Workflow success prior to pull request merge

### ISSUE THREAD

**Issue by geerzo** [Best-DevOps-Hackathon-Team-3/openhack-devops-team#11]
Please describe the process change:
The workflow needs to run and pass before a PR can be merged

Please describe the value to the project of the change:
Don't merge bad stuff

**Comment by Briwalkr** [comment]
Check the box. 

![Policy](https://user-images.githubusercontent.com/10443706/128935950-f2a1dbc0-eafd-4178-b27d-632624ae9884.JPG)
