### ISSUE TITLE
Ensure POI API Workflow creates a bug issue if workflow fails

### ISSUE THREAD

**Issue by geerzo** [Best-DevOps-Hackathon-Team-3/openhack-devops-team#12]
Please describe the process change:
Workflow creates bug for any failed runs

Please describe the value to the project of the change:
Track all the bad stuff we do

**Comment by rshelat97** [comment]
![image](https://user-images.githubusercontent.com/35717316/128936428-82123e32-90ba-41a3-b536-5fda86b772bb.png)
Syntax for if step fails.

**Comment by rshelat97** [comment]
https://github.com/marketplace/actions/create-an-issue

Github action to create bug-issue for when step fails
