### ISSUE TITLE
Update existing POI and Trips master workflows to deploy to staging

### ISSUE THREAD

**Issue by geerzo** [Best-DevOps-Hackathon-Team-3/openhack-devops-team#40]
- [ ] Update Workflow step to use staging
- [ ] Upload staging profiles

**Comment by sumeetranu** [comment]
https://openhackzl57ob94trips-staging.azurewebsites.net/api/healthcheck/trips
https://openhackzl57ob94poi-staging.azurewebsites.net/api/healthcheck/poi
